[package]
name = "runner"
version = "0.1.0"
edition = "2024"


[dependencies]
render_api = { path = "../render_api" }
core = { path = "../core" }
renderer = { path = "../renderer_vulkan" }
winit = "0.29.15"
raw-window-handle = "0.6"
nalgebra = "0.33"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

