[package]
name = "render_api"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33"
glam = { version = "0.33.2", features = ["bytemuck"] }
bytemuck = { version = "1.25.2", features = ["derive"] }
shared = { path = "../shared" }
thiserror = "2.0.19"
ash = "0.38.0"
cxx = "1.0"
cmake = "0.1.58"
flatbuffers = "25.12.19"

[build-dependencies]
# build.rs内でCMakeを起動するためのクレート
cmake = "0.1"
cxx-build = "1.0"
