#include "generator_core.h"
#include <format>
#include <string>
#include <expected>

namespace rey_engine::slang_generator {

    std::expected<std::string, std::string> generate_cpp_bindings(const ResourceBindingsSoA& soa_data) {
        // ステップ1：入力データの検証（早期リターン）
        if (soa_data.names.empty()) {
            return std::unexpected("No resources to generate.");
        }

        std::string out;

        // ステップ2：ヘッダと名前空間の書き込み
        out += std::format("// ==========================================\n");
        out += std::format("// Auto-generated by Rey Engine Slang Generator\n");
        out += std::format("// DO NOT EDIT DIRECTLY\n");
        out += std::format("// ==========================================\n");
        out += std::format("#pragma once\n\n");
        out += std::format("#include <cstdint>\n\n");
        out += std::format("namespace rey_engine::generated {{\n\n");

        // ステップ3：マジックナンバー排除のための定数生成
        for (size_t i = 0; i < soa_data.names.size(); ++i) {
            const auto& name = soa_data.names[i];
            const uint32_t set = soa_data.sets[i];
            const uint32_t binding = soa_data.bindings[i];

            // C++23の std::format により、直感的に変数を埋め込める
            out += std::format("    constexpr uint32_t SET_{} = {};\n", name, set);
            out += std::format("    constexpr uint32_t BINDING_{} = {};\n\n", name, binding);
        }

        // ステップ4：Vulkan向け構築用のメタデータ配列化など（一例）
        out += std::format("    // 実行時にVulkanのレイアウトを組むための静的配列など\n");
        out += std::format("    constexpr uint32_t TOTAL_BINDINGS = {};\n\n", soa_data.names.size());

        // ステップ5：名前空間のクローズと結果の返却
        out += std::format("}}  // namespace rey_engine::generated\n");

        return out;
    }

}  // namespace rey_engine::slang_generator
